services:
  trash-alert:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: unless-stopped
